name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Prepare
        run: yarn install

      - name: Lint
        run: yarn lint:ts

      - name: Build
        run: yarn build

      - name: Generate
        run: yarn generate

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: devjang/nuxt-realworld:latest
